//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HOOVERModel", "FK_DailyFuelLog_Equipment_EquipmentId", "Equipment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hoover.Models.Equipment), "DailyFuelLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hoover.Models.DailyFuelLog), true)]

#endregion

namespace Hoover.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HOOVEREntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HOOVEREntities object using the connection string found in the 'HOOVEREntities' section of the application configuration file.
        /// </summary>
        public HOOVEREntities() : base("name=HOOVEREntities", "HOOVEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HOOVEREntities object.
        /// </summary>
        public HOOVEREntities(string connectionString) : base(connectionString, "HOOVEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HOOVEREntities object.
        /// </summary>
        public HOOVEREntities(EntityConnection connection) : base(connection, "HOOVEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DailyFuelLog> DailyFuelLog
        {
            get
            {
                if ((_DailyFuelLog == null))
                {
                    _DailyFuelLog = base.CreateObjectSet<DailyFuelLog>("DailyFuelLog");
                }
                return _DailyFuelLog;
            }
        }
        private ObjectSet<DailyFuelLog> _DailyFuelLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Equipment> Equipment
        {
            get
            {
                if ((_Equipment == null))
                {
                    _Equipment = base.CreateObjectSet<Equipment>("Equipment");
                }
                return _Equipment;
            }
        }
        private ObjectSet<Equipment> _Equipment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<JobMaintLog> JobMaintLog
        {
            get
            {
                if ((_JobMaintLog == null))
                {
                    _JobMaintLog = base.CreateObjectSet<JobMaintLog>("JobMaintLog");
                }
                return _JobMaintLog;
            }
        }
        private ObjectSet<JobMaintLog> _JobMaintLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaintCheck> MaintCheck
        {
            get
            {
                if ((_MaintCheck == null))
                {
                    _MaintCheck = base.CreateObjectSet<MaintCheck>("MaintCheck");
                }
                return _MaintCheck;
            }
        }
        private ObjectSet<MaintCheck> _MaintCheck;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaintCheckLog> MaintCheckLog
        {
            get
            {
                if ((_MaintCheckLog == null))
                {
                    _MaintCheckLog = base.CreateObjectSet<MaintCheckLog>("MaintCheckLog");
                }
                return _MaintCheckLog;
            }
        }
        private ObjectSet<MaintCheckLog> _MaintCheckLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaintCheckPartsNotesLog> MaintCheckPartsNotesLog
        {
            get
            {
                if ((_MaintCheckPartsNotesLog == null))
                {
                    _MaintCheckPartsNotesLog = base.CreateObjectSet<MaintCheckPartsNotesLog>("MaintCheckPartsNotesLog");
                }
                return _MaintCheckPartsNotesLog;
            }
        }
        private ObjectSet<MaintCheckPartsNotesLog> _MaintCheckPartsNotesLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaintCheckStep> MaintCheckStep
        {
            get
            {
                if ((_MaintCheckStep == null))
                {
                    _MaintCheckStep = base.CreateObjectSet<MaintCheckStep>("MaintCheckStep");
                }
                return _MaintCheckStep;
            }
        }
        private ObjectSet<MaintCheckStep> _MaintCheckStep;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaintSchedule> MaintSchedule
        {
            get
            {
                if ((_MaintSchedule == null))
                {
                    _MaintSchedule = base.CreateObjectSet<MaintSchedule>("MaintSchedule");
                }
                return _MaintSchedule;
            }
        }
        private ObjectSet<MaintSchedule> _MaintSchedule;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Parts> Parts
        {
            get
            {
                if ((_Parts == null))
                {
                    _Parts = base.CreateObjectSet<Parts>("Parts");
                }
                return _Parts;
            }
        }
        private ObjectSet<Parts> _Parts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DailyFuelLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDailyFuelLog(DailyFuelLog dailyFuelLog)
        {
            base.AddObject("DailyFuelLog", dailyFuelLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Equipment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipment(Equipment equipment)
        {
            base.AddObject("Equipment", equipment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the JobMaintLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJobMaintLog(JobMaintLog jobMaintLog)
        {
            base.AddObject("JobMaintLog", jobMaintLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaintCheck EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaintCheck(MaintCheck maintCheck)
        {
            base.AddObject("MaintCheck", maintCheck);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaintCheckLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaintCheckLog(MaintCheckLog maintCheckLog)
        {
            base.AddObject("MaintCheckLog", maintCheckLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaintCheckPartsNotesLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaintCheckPartsNotesLog(MaintCheckPartsNotesLog maintCheckPartsNotesLog)
        {
            base.AddObject("MaintCheckPartsNotesLog", maintCheckPartsNotesLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaintCheckStep EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaintCheckStep(MaintCheckStep maintCheckStep)
        {
            base.AddObject("MaintCheckStep", maintCheckStep);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaintSchedule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaintSchedule(MaintSchedule maintSchedule)
        {
            base.AddObject("MaintSchedule", maintSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Parts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParts(Parts parts)
        {
            base.AddObject("Parts", parts);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="DailyFuelLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DailyFuelLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DailyFuelLog object.
        /// </summary>
        /// <param name="dailyFueLogId">Initial value of the DailyFueLogId property.</param>
        /// <param name="equipmentId">Initial value of the EquipmentId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static DailyFuelLog CreateDailyFuelLog(global::System.Int64 dailyFueLogId, global::System.Int32 equipmentId, global::System.DateTime date)
        {
            DailyFuelLog dailyFuelLog = new DailyFuelLog();
            dailyFuelLog.DailyFueLogId = dailyFueLogId;
            dailyFuelLog.EquipmentId = equipmentId;
            dailyFuelLog.Date = date;
            return dailyFuelLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DailyFueLogId
        {
            get
            {
                return _DailyFueLogId;
            }
            set
            {
                if (_DailyFueLogId != value)
                {
                    OnDailyFueLogIdChanging(value);
                    ReportPropertyChanging("DailyFueLogId");
                    _DailyFueLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DailyFueLogId");
                    OnDailyFueLogIdChanged();
                }
            }
        }
        private global::System.Int64 _DailyFueLogId;
        partial void OnDailyFueLogIdChanging(global::System.Int64 value);
        partial void OnDailyFueLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentId
        {
            get
            {
                return _EquipmentId;
            }
            set
            {
                OnEquipmentIdChanging(value);
                ReportPropertyChanging("EquipmentId");
                _EquipmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentId");
                OnEquipmentIdChanged();
            }
        }
        private global::System.Int32 _EquipmentId;
        partial void OnEquipmentIdChanging(global::System.Int32 value);
        partial void OnEquipmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MeterReading
        {
            get
            {
                return _MeterReading;
            }
            set
            {
                OnMeterReadingChanging(value);
                ReportPropertyChanging("MeterReading");
                _MeterReading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeterReading");
                OnMeterReadingChanged();
            }
        }
        private Nullable<global::System.Decimal> _MeterReading;
        partial void OnMeterReadingChanging(Nullable<global::System.Decimal> value);
        partial void OnMeterReadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Fuel
        {
            get
            {
                return _Fuel;
            }
            set
            {
                OnFuelChanging(value);
                ReportPropertyChanging("Fuel");
                _Fuel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fuel");
                OnFuelChanged();
            }
        }
        private Nullable<global::System.Decimal> _Fuel;
        partial void OnFuelChanging(Nullable<global::System.Decimal> value);
        partial void OnFuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EngineOil
        {
            get
            {
                return _EngineOil;
            }
            set
            {
                OnEngineOilChanging(value);
                ReportPropertyChanging("EngineOil");
                _EngineOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EngineOil");
                OnEngineOilChanged();
            }
        }
        private Nullable<global::System.Decimal> _EngineOil;
        partial void OnEngineOilChanging(Nullable<global::System.Decimal> value);
        partial void OnEngineOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GearOil
        {
            get
            {
                return _GearOil;
            }
            set
            {
                OnGearOilChanging(value);
                ReportPropertyChanging("GearOil");
                _GearOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GearOil");
                OnGearOilChanged();
            }
        }
        private Nullable<global::System.Decimal> _GearOil;
        partial void OnGearOilChanging(Nullable<global::System.Decimal> value);
        partial void OnGearOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HydrolicOil
        {
            get
            {
                return _HydrolicOil;
            }
            set
            {
                OnHydrolicOilChanging(value);
                ReportPropertyChanging("HydrolicOil");
                _HydrolicOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HydrolicOil");
                OnHydrolicOilChanged();
            }
        }
        private Nullable<global::System.Decimal> _HydrolicOil;
        partial void OnHydrolicOilChanging(Nullable<global::System.Decimal> value);
        partial void OnHydrolicOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RepairNotes
        {
            get
            {
                return _RepairNotes;
            }
            set
            {
                OnRepairNotesChanging(value);
                ReportPropertyChanging("RepairNotes");
                _RepairNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RepairNotes");
                OnRepairNotesChanged();
            }
        }
        private global::System.String _RepairNotes;
        partial void OnRepairNotesChanging(global::System.String value);
        partial void OnRepairNotesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HOOVERModel", "FK_DailyFuelLog_Equipment_EquipmentId", "Equipment")]
        public Equipment Equipment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "Equipment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "Equipment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipment> EquipmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipment>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "Equipment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipment>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "Equipment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="Equipment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Equipment object.
        /// </summary>
        /// <param name="equipmentId">Initial value of the EquipmentId property.</param>
        /// <param name="equipmentNumber">Initial value of the EquipmentNumber property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        public static Equipment CreateEquipment(global::System.Int32 equipmentId, global::System.String equipmentNumber, global::System.String model)
        {
            Equipment equipment = new Equipment();
            equipment.EquipmentId = equipmentId;
            equipment.EquipmentNumber = equipmentNumber;
            equipment.Model = model;
            return equipment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentId
        {
            get
            {
                return _EquipmentId;
            }
            set
            {
                if (_EquipmentId != value)
                {
                    OnEquipmentIdChanging(value);
                    ReportPropertyChanging("EquipmentId");
                    _EquipmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EquipmentId");
                    OnEquipmentIdChanged();
                }
            }
        }
        private global::System.Int32 _EquipmentId;
        partial void OnEquipmentIdChanging(global::System.Int32 value);
        partial void OnEquipmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EquipmentNumber
        {
            get
            {
                return _EquipmentNumber;
            }
            set
            {
                OnEquipmentNumberChanging(value);
                ReportPropertyChanging("EquipmentNumber");
                _EquipmentNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EquipmentNumber");
                OnEquipmentNumberChanged();
            }
        }
        private global::System.String _EquipmentNumber;
        partial void OnEquipmentNumberChanging(global::System.String value);
        partial void OnEquipmentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SerialNumber
        {
            get
            {
                return _SerialNumber;
            }
            set
            {
                OnSerialNumberChanging(value);
                ReportPropertyChanging("SerialNumber");
                _SerialNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SerialNumber");
                OnSerialNumberChanged();
            }
        }
        private global::System.String _SerialNumber;
        partial void OnSerialNumberChanging(global::System.String value);
        partial void OnSerialNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HOOVERModel", "FK_DailyFuelLog_Equipment_EquipmentId", "DailyFuelLog")]
        public EntityCollection<DailyFuelLog> DailyFuelLog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DailyFuelLog>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "DailyFuelLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DailyFuelLog>("HOOVERModel.FK_DailyFuelLog_Equipment_EquipmentId", "DailyFuelLog", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="JobMaintLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JobMaintLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new JobMaintLog object.
        /// </summary>
        /// <param name="maintId">Initial value of the MaintId property.</param>
        /// <param name="maintDate">Initial value of the MaintDate property.</param>
        /// <param name="jobId">Initial value of the JobId property.</param>
        /// <param name="meterHours">Initial value of the MeterHours property.</param>
        /// <param name="accumOprHours">Initial value of the AccumOprHours property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static JobMaintLog CreateJobMaintLog(global::System.Int32 maintId, global::System.DateTime maintDate, global::System.String jobId, global::System.Int32 meterHours, global::System.Int32 accumOprHours, global::System.Int32 userId)
        {
            JobMaintLog jobMaintLog = new JobMaintLog();
            jobMaintLog.MaintId = maintId;
            jobMaintLog.MaintDate = maintDate;
            jobMaintLog.JobId = jobId;
            jobMaintLog.MeterHours = meterHours;
            jobMaintLog.AccumOprHours = accumOprHours;
            jobMaintLog.UserId = userId;
            return jobMaintLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintId
        {
            get
            {
                return _MaintId;
            }
            set
            {
                if (_MaintId != value)
                {
                    OnMaintIdChanging(value);
                    ReportPropertyChanging("MaintId");
                    _MaintId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintId");
                    OnMaintIdChanged();
                }
            }
        }
        private global::System.Int32 _MaintId;
        partial void OnMaintIdChanging(global::System.Int32 value);
        partial void OnMaintIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MaintDate
        {
            get
            {
                return _MaintDate;
            }
            set
            {
                OnMaintDateChanging(value);
                ReportPropertyChanging("MaintDate");
                _MaintDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintDate");
                OnMaintDateChanged();
            }
        }
        private global::System.DateTime _MaintDate;
        partial void OnMaintDateChanging(global::System.DateTime value);
        partial void OnMaintDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobId
        {
            get
            {
                return _JobId;
            }
            set
            {
                OnJobIdChanging(value);
                ReportPropertyChanging("JobId");
                _JobId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JobId");
                OnJobIdChanged();
            }
        }
        private global::System.String _JobId;
        partial void OnJobIdChanging(global::System.String value);
        partial void OnJobIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeterHours
        {
            get
            {
                return _MeterHours;
            }
            set
            {
                OnMeterHoursChanging(value);
                ReportPropertyChanging("MeterHours");
                _MeterHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeterHours");
                OnMeterHoursChanged();
            }
        }
        private global::System.Int32 _MeterHours;
        partial void OnMeterHoursChanging(global::System.Int32 value);
        partial void OnMeterHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccumOprHours
        {
            get
            {
                return _AccumOprHours;
            }
            set
            {
                OnAccumOprHoursChanging(value);
                ReportPropertyChanging("AccumOprHours");
                _AccumOprHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccumOprHours");
                OnAccumOprHoursChanged();
            }
        }
        private global::System.Int32 _AccumOprHours;
        partial void OnAccumOprHoursChanging(global::System.Int32 value);
        partial void OnAccumOprHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fuel
        {
            get
            {
                return _Fuel;
            }
            set
            {
                OnFuelChanging(value);
                ReportPropertyChanging("Fuel");
                _Fuel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fuel");
                OnFuelChanged();
            }
        }
        private Nullable<global::System.Int32> _Fuel;
        partial void OnFuelChanging(Nullable<global::System.Int32> value);
        partial void OnFuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MotorOil
        {
            get
            {
                return _MotorOil;
            }
            set
            {
                OnMotorOilChanging(value);
                ReportPropertyChanging("MotorOil");
                _MotorOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MotorOil");
                OnMotorOilChanged();
            }
        }
        private Nullable<global::System.Int32> _MotorOil;
        partial void OnMotorOilChanging(Nullable<global::System.Int32> value);
        partial void OnMotorOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TransOil
        {
            get
            {
                return _TransOil;
            }
            set
            {
                OnTransOilChanging(value);
                ReportPropertyChanging("TransOil");
                _TransOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransOil");
                OnTransOilChanged();
            }
        }
        private Nullable<global::System.Int32> _TransOil;
        partial void OnTransOilChanging(Nullable<global::System.Int32> value);
        partial void OnTransOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HydOil
        {
            get
            {
                return _HydOil;
            }
            set
            {
                OnHydOilChanging(value);
                ReportPropertyChanging("HydOil");
                _HydOil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HydOil");
                OnHydOilChanged();
            }
        }
        private Nullable<global::System.Int32> _HydOil;
        partial void OnHydOilChanging(Nullable<global::System.Int32> value);
        partial void OnHydOilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FinalDrive
        {
            get
            {
                return _FinalDrive;
            }
            set
            {
                OnFinalDriveChanging(value);
                ReportPropertyChanging("FinalDrive");
                _FinalDrive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalDrive");
                OnFinalDriveChanged();
            }
        }
        private Nullable<global::System.Int32> _FinalDrive;
        partial void OnFinalDriveChanging(Nullable<global::System.Int32> value);
        partial void OnFinalDriveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AntiFreeze
        {
            get
            {
                return _AntiFreeze;
            }
            set
            {
                OnAntiFreezeChanging(value);
                ReportPropertyChanging("AntiFreeze");
                _AntiFreeze = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AntiFreeze");
                OnAntiFreezeChanged();
            }
        }
        private Nullable<global::System.Int32> _AntiFreeze;
        partial void OnAntiFreezeChanging(Nullable<global::System.Int32> value);
        partial void OnAntiFreezeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="MaintCheck")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaintCheck : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaintCheck object.
        /// </summary>
        /// <param name="maintCheckId">Initial value of the MaintCheckId property.</param>
        /// <param name="maintCheckName">Initial value of the MaintCheckName property.</param>
        /// <param name="interval">Initial value of the Interval property.</param>
        /// <param name="intervalTypeId">Initial value of the IntervalTypeId property.</param>
        public static MaintCheck CreateMaintCheck(global::System.Int32 maintCheckId, global::System.String maintCheckName, global::System.Int32 interval, global::System.Int32 intervalTypeId)
        {
            MaintCheck maintCheck = new MaintCheck();
            maintCheck.MaintCheckId = maintCheckId;
            maintCheck.MaintCheckName = maintCheckName;
            maintCheck.Interval = interval;
            maintCheck.IntervalTypeId = intervalTypeId;
            return maintCheck;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckId
        {
            get
            {
                return _MaintCheckId;
            }
            set
            {
                if (_MaintCheckId != value)
                {
                    OnMaintCheckIdChanging(value);
                    ReportPropertyChanging("MaintCheckId");
                    _MaintCheckId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintCheckId");
                    OnMaintCheckIdChanged();
                }
            }
        }
        private global::System.Int32 _MaintCheckId;
        partial void OnMaintCheckIdChanging(global::System.Int32 value);
        partial void OnMaintCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaintCheckName
        {
            get
            {
                return _MaintCheckName;
            }
            set
            {
                OnMaintCheckNameChanging(value);
                ReportPropertyChanging("MaintCheckName");
                _MaintCheckName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaintCheckName");
                OnMaintCheckNameChanged();
            }
        }
        private global::System.String _MaintCheckName;
        partial void OnMaintCheckNameChanging(global::System.String value);
        partial void OnMaintCheckNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaintCheckDesctription
        {
            get
            {
                return _MaintCheckDesctription;
            }
            set
            {
                OnMaintCheckDesctriptionChanging(value);
                ReportPropertyChanging("MaintCheckDesctription");
                _MaintCheckDesctription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaintCheckDesctription");
                OnMaintCheckDesctriptionChanged();
            }
        }
        private global::System.String _MaintCheckDesctription;
        partial void OnMaintCheckDesctriptionChanging(global::System.String value);
        partial void OnMaintCheckDesctriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Interval
        {
            get
            {
                return _Interval;
            }
            set
            {
                OnIntervalChanging(value);
                ReportPropertyChanging("Interval");
                _Interval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Interval");
                OnIntervalChanged();
            }
        }
        private global::System.Int32 _Interval;
        partial void OnIntervalChanging(global::System.Int32 value);
        partial void OnIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IntervalTypeId
        {
            get
            {
                return _IntervalTypeId;
            }
            set
            {
                OnIntervalTypeIdChanging(value);
                ReportPropertyChanging("IntervalTypeId");
                _IntervalTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IntervalTypeId");
                OnIntervalTypeIdChanged();
            }
        }
        private global::System.Int32 _IntervalTypeId;
        partial void OnIntervalTypeIdChanging(global::System.Int32 value);
        partial void OnIntervalTypeIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="MaintCheckLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaintCheckLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaintCheckLog object.
        /// </summary>
        /// <param name="maintCheckLogId">Initial value of the MaintCheckLogId property.</param>
        /// <param name="maintCheckLogDate">Initial value of the MaintCheckLogDate property.</param>
        /// <param name="equipmentId">Initial value of the EquipmentId property.</param>
        /// <param name="maintCheckId">Initial value of the MaintCheckId property.</param>
        /// <param name="actualReading">Initial value of the ActualReading property.</param>
        public static MaintCheckLog CreateMaintCheckLog(global::System.Int32 maintCheckLogId, global::System.DateTime maintCheckLogDate, global::System.Int32 equipmentId, global::System.Int32 maintCheckId, global::System.Int32 actualReading)
        {
            MaintCheckLog maintCheckLog = new MaintCheckLog();
            maintCheckLog.MaintCheckLogId = maintCheckLogId;
            maintCheckLog.MaintCheckLogDate = maintCheckLogDate;
            maintCheckLog.EquipmentId = equipmentId;
            maintCheckLog.MaintCheckId = maintCheckId;
            maintCheckLog.ActualReading = actualReading;
            return maintCheckLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckLogId
        {
            get
            {
                return _MaintCheckLogId;
            }
            set
            {
                if (_MaintCheckLogId != value)
                {
                    OnMaintCheckLogIdChanging(value);
                    ReportPropertyChanging("MaintCheckLogId");
                    _MaintCheckLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintCheckLogId");
                    OnMaintCheckLogIdChanged();
                }
            }
        }
        private global::System.Int32 _MaintCheckLogId;
        partial void OnMaintCheckLogIdChanging(global::System.Int32 value);
        partial void OnMaintCheckLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MaintCheckLogDate
        {
            get
            {
                return _MaintCheckLogDate;
            }
            set
            {
                OnMaintCheckLogDateChanging(value);
                ReportPropertyChanging("MaintCheckLogDate");
                _MaintCheckLogDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCheckLogDate");
                OnMaintCheckLogDateChanged();
            }
        }
        private global::System.DateTime _MaintCheckLogDate;
        partial void OnMaintCheckLogDateChanging(global::System.DateTime value);
        partial void OnMaintCheckLogDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentId
        {
            get
            {
                return _EquipmentId;
            }
            set
            {
                OnEquipmentIdChanging(value);
                ReportPropertyChanging("EquipmentId");
                _EquipmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentId");
                OnEquipmentIdChanged();
            }
        }
        private global::System.Int32 _EquipmentId;
        partial void OnEquipmentIdChanging(global::System.Int32 value);
        partial void OnEquipmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckId
        {
            get
            {
                return _MaintCheckId;
            }
            set
            {
                OnMaintCheckIdChanging(value);
                ReportPropertyChanging("MaintCheckId");
                _MaintCheckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCheckId");
                OnMaintCheckIdChanged();
            }
        }
        private global::System.Int32 _MaintCheckId;
        partial void OnMaintCheckIdChanging(global::System.Int32 value);
        partial void OnMaintCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActualReading
        {
            get
            {
                return _ActualReading;
            }
            set
            {
                OnActualReadingChanging(value);
                ReportPropertyChanging("ActualReading");
                _ActualReading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualReading");
                OnActualReadingChanged();
            }
        }
        private global::System.Int32 _ActualReading;
        partial void OnActualReadingChanging(global::System.Int32 value);
        partial void OnActualReadingChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="MaintCheckPartsNotesLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaintCheckPartsNotesLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaintCheckPartsNotesLog object.
        /// </summary>
        /// <param name="maintCheckPartsNotesLog1">Initial value of the MaintCheckPartsNotesLog1 property.</param>
        /// <param name="maintCheckLogId">Initial value of the MaintCheckLogId property.</param>
        public static MaintCheckPartsNotesLog CreateMaintCheckPartsNotesLog(global::System.Int32 maintCheckPartsNotesLog1, global::System.Int32 maintCheckLogId)
        {
            MaintCheckPartsNotesLog maintCheckPartsNotesLog = new MaintCheckPartsNotesLog();
            maintCheckPartsNotesLog.MaintCheckPartsNotesLog1 = maintCheckPartsNotesLog1;
            maintCheckPartsNotesLog.MaintCheckLogId = maintCheckLogId;
            return maintCheckPartsNotesLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckPartsNotesLog1
        {
            get
            {
                return _MaintCheckPartsNotesLog1;
            }
            set
            {
                if (_MaintCheckPartsNotesLog1 != value)
                {
                    OnMaintCheckPartsNotesLog1Changing(value);
                    ReportPropertyChanging("MaintCheckPartsNotesLog1");
                    _MaintCheckPartsNotesLog1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintCheckPartsNotesLog1");
                    OnMaintCheckPartsNotesLog1Changed();
                }
            }
        }
        private global::System.Int32 _MaintCheckPartsNotesLog1;
        partial void OnMaintCheckPartsNotesLog1Changing(global::System.Int32 value);
        partial void OnMaintCheckPartsNotesLog1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckLogId
        {
            get
            {
                return _MaintCheckLogId;
            }
            set
            {
                OnMaintCheckLogIdChanging(value);
                ReportPropertyChanging("MaintCheckLogId");
                _MaintCheckLogId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCheckLogId");
                OnMaintCheckLogIdChanged();
            }
        }
        private global::System.Int32 _MaintCheckLogId;
        partial void OnMaintCheckLogIdChanging(global::System.Int32 value);
        partial void OnMaintCheckLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PartsId
        {
            get
            {
                return _PartsId;
            }
            set
            {
                OnPartsIdChanging(value);
                ReportPropertyChanging("PartsId");
                _PartsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartsId");
                OnPartsIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PartsId;
        partial void OnPartsIdChanging(Nullable<global::System.Int32> value);
        partial void OnPartsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RepairNotes
        {
            get
            {
                return _RepairNotes;
            }
            set
            {
                OnRepairNotesChanging(value);
                ReportPropertyChanging("RepairNotes");
                _RepairNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RepairNotes");
                OnRepairNotesChanged();
            }
        }
        private global::System.String _RepairNotes;
        partial void OnRepairNotesChanging(global::System.String value);
        partial void OnRepairNotesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="MaintCheckStep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaintCheckStep : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaintCheckStep object.
        /// </summary>
        /// <param name="maintCheckStepId">Initial value of the MaintCheckStepId property.</param>
        /// <param name="maintCheckId">Initial value of the MaintCheckId property.</param>
        /// <param name="stepDescription">Initial value of the StepDescription property.</param>
        /// <param name="deprecated">Initial value of the Deprecated property.</param>
        public static MaintCheckStep CreateMaintCheckStep(global::System.Int32 maintCheckStepId, global::System.Int32 maintCheckId, global::System.String stepDescription, global::System.Boolean deprecated)
        {
            MaintCheckStep maintCheckStep = new MaintCheckStep();
            maintCheckStep.MaintCheckStepId = maintCheckStepId;
            maintCheckStep.MaintCheckId = maintCheckId;
            maintCheckStep.StepDescription = stepDescription;
            maintCheckStep.Deprecated = deprecated;
            return maintCheckStep;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckStepId
        {
            get
            {
                return _MaintCheckStepId;
            }
            set
            {
                if (_MaintCheckStepId != value)
                {
                    OnMaintCheckStepIdChanging(value);
                    ReportPropertyChanging("MaintCheckStepId");
                    _MaintCheckStepId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintCheckStepId");
                    OnMaintCheckStepIdChanged();
                }
            }
        }
        private global::System.Int32 _MaintCheckStepId;
        partial void OnMaintCheckStepIdChanging(global::System.Int32 value);
        partial void OnMaintCheckStepIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckId
        {
            get
            {
                return _MaintCheckId;
            }
            set
            {
                OnMaintCheckIdChanging(value);
                ReportPropertyChanging("MaintCheckId");
                _MaintCheckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCheckId");
                OnMaintCheckIdChanged();
            }
        }
        private global::System.Int32 _MaintCheckId;
        partial void OnMaintCheckIdChanging(global::System.Int32 value);
        partial void OnMaintCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StepDescription
        {
            get
            {
                return _StepDescription;
            }
            set
            {
                OnStepDescriptionChanging(value);
                ReportPropertyChanging("StepDescription");
                _StepDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StepDescription");
                OnStepDescriptionChanged();
            }
        }
        private global::System.String _StepDescription;
        partial void OnStepDescriptionChanging(global::System.String value);
        partial void OnStepDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deprecated
        {
            get
            {
                return _Deprecated;
            }
            set
            {
                OnDeprecatedChanging(value);
                ReportPropertyChanging("Deprecated");
                _Deprecated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deprecated");
                OnDeprecatedChanged();
            }
        }
        private global::System.Boolean _Deprecated;
        partial void OnDeprecatedChanging(global::System.Boolean value);
        partial void OnDeprecatedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="MaintSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaintSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaintSchedule object.
        /// </summary>
        /// <param name="maintScheduleId">Initial value of the MaintScheduleId property.</param>
        /// <param name="equipmentId">Initial value of the EquipmentId property.</param>
        /// <param name="maintCheckId">Initial value of the MaintCheckId property.</param>
        public static MaintSchedule CreateMaintSchedule(global::System.Int32 maintScheduleId, global::System.Int32 equipmentId, global::System.Int32 maintCheckId)
        {
            MaintSchedule maintSchedule = new MaintSchedule();
            maintSchedule.MaintScheduleId = maintScheduleId;
            maintSchedule.EquipmentId = equipmentId;
            maintSchedule.MaintCheckId = maintCheckId;
            return maintSchedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintScheduleId
        {
            get
            {
                return _MaintScheduleId;
            }
            set
            {
                if (_MaintScheduleId != value)
                {
                    OnMaintScheduleIdChanging(value);
                    ReportPropertyChanging("MaintScheduleId");
                    _MaintScheduleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaintScheduleId");
                    OnMaintScheduleIdChanged();
                }
            }
        }
        private global::System.Int32 _MaintScheduleId;
        partial void OnMaintScheduleIdChanging(global::System.Int32 value);
        partial void OnMaintScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentId
        {
            get
            {
                return _EquipmentId;
            }
            set
            {
                OnEquipmentIdChanging(value);
                ReportPropertyChanging("EquipmentId");
                _EquipmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentId");
                OnEquipmentIdChanged();
            }
        }
        private global::System.Int32 _EquipmentId;
        partial void OnEquipmentIdChanging(global::System.Int32 value);
        partial void OnEquipmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintCheckId
        {
            get
            {
                return _MaintCheckId;
            }
            set
            {
                OnMaintCheckIdChanging(value);
                ReportPropertyChanging("MaintCheckId");
                _MaintCheckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCheckId");
                OnMaintCheckIdChanged();
            }
        }
        private global::System.Int32 _MaintCheckId;
        partial void OnMaintCheckIdChanging(global::System.Int32 value);
        partial void OnMaintCheckIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HOOVERModel", Name="Parts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Parts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Parts object.
        /// </summary>
        /// <param name="partsId">Initial value of the PartsId property.</param>
        /// <param name="partName">Initial value of the PartName property.</param>
        public static Parts CreateParts(global::System.Int32 partsId, global::System.String partName)
        {
            Parts parts = new Parts();
            parts.PartsId = partsId;
            parts.PartName = partName;
            return parts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartsId
        {
            get
            {
                return _PartsId;
            }
            set
            {
                if (_PartsId != value)
                {
                    OnPartsIdChanging(value);
                    ReportPropertyChanging("PartsId");
                    _PartsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PartsId");
                    OnPartsIdChanged();
                }
            }
        }
        private global::System.Int32 _PartsId;
        partial void OnPartsIdChanging(global::System.Int32 value);
        partial void OnPartsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PartName
        {
            get
            {
                return _PartName;
            }
            set
            {
                OnPartNameChanging(value);
                ReportPropertyChanging("PartName");
                _PartName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PartName");
                OnPartNameChanged();
            }
        }
        private global::System.String _PartName;
        partial void OnPartNameChanging(global::System.String value);
        partial void OnPartNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartModelNumber
        {
            get
            {
                return _PartModelNumber;
            }
            set
            {
                OnPartModelNumberChanging(value);
                ReportPropertyChanging("PartModelNumber");
                _PartModelNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PartModelNumber");
                OnPartModelNumberChanged();
            }
        }
        private global::System.String _PartModelNumber;
        partial void OnPartModelNumberChanging(global::System.String value);
        partial void OnPartModelNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartDescription
        {
            get
            {
                return _PartDescription;
            }
            set
            {
                OnPartDescriptionChanging(value);
                ReportPropertyChanging("PartDescription");
                _PartDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PartDescription");
                OnPartDescriptionChanged();
            }
        }
        private global::System.String _PartDescription;
        partial void OnPartDescriptionChanging(global::System.String value);
        partial void OnPartDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PartCost
        {
            get
            {
                return _PartCost;
            }
            set
            {
                OnPartCostChanging(value);
                ReportPropertyChanging("PartCost");
                _PartCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartCost");
                OnPartCostChanged();
            }
        }
        private Nullable<global::System.Decimal> _PartCost;
        partial void OnPartCostChanging(Nullable<global::System.Decimal> value);
        partial void OnPartCostChanged();

        #endregion

    
    }

    #endregion

    
}
